### ISSUE TITLE
PlayerInteractEvent   error

### ISSUE THREAD

**Issue by ausir0726** [softpak/HOSE#12]
```command
[20:41:04 ERROR]: Could not pass event PlayerInteractEvent to GriefPrevention v13.9.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:668) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:567) [hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/permission/RegionPermissionModel
        at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:29) ~[?:?]
        at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:820) ~[?:?]
        at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2440) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[hose-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        ... 17 more


`

**Comment by softpak** [comment]
這看起來是插件版本錯誤導致。

**Comment by ausir0726** [comment]
稍晚檢查更新以及更新 HOSE 後回報，謝謝。

**Comment by ausir0726** [comment]
似乎是 GriefPrevention 目前僅支援到 1.9 還沒到 1.9.2

後續追蹤
