### ISSUE TITLE
今天 build 的時候發生的錯誤

### ISSUE THREAD

**Issue by ausir0726** [softpak/HOSE#14]
今天 build 的時候發生的錯誤

``` bash

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spigot 1.9.2-R0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spigot ---
[INFO] Deleting /Users/ausir/mcbuilder/Spigot/Spigot-Server/target
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ spigot ---
[INFO]
[INFO] --- scriptus:0.2:describe (ex-spigot) @ spigot ---
[INFO] Set property "spigot.desc" to "git-Spigot-944aa20"
[INFO]
[INFO] --- scriptus:0.2:describe (ex-craftbukkit) @ spigot ---
[INFO] Set property "craftbukkit.desc" to "-8d16fc0"
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spigot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ spigot ---
[INFO] Changes detected - recompiling the module!
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/ausir/mcbuilder/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityPlayer.java:[39] Type mismatch: cannot convert from List<Object> to List<Integer>
[ERROR] /Users/ausir/mcbuilder/Spigot/Spigot-Server/src/main/java/net/minecraft/server/PlayerChunkMap.java:[49] Type mismatch: cannot convert from List<Object> to List<PlayerChunk>
[ERROR] /Users/ausir/mcbuilder/Spigot/Spigot-Server/src/main/java/net/minecraft/server/PlayerChunkMap.java:[51] Type mismatch: cannot convert from List<Object> to List<PlayerChunk>
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.376 s
[INFO] Finished at: 2016-04-08T09:59:26+08:00
[INFO] Final Memory: 22M/398M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spigot: Compilation failure: Compilation failure:
[ERROR] /Users/ausir/mcbuilder/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityPlayer.java:[39] Type mismatch: cannot convert from List<Object> to List<Integer>
[ERROR] /Users/ausir/mcbuilder/Spigot/Spigot-Server/src/main/java/net/minecraft/server/PlayerChunkMap.java:[49] Type mismatch: cannot convert from List<Object> to List<PlayerChunk>
[ERROR] /Users/ausir/mcbuilder/Spigot/Spigot-Server/src/main/java/net/minecraft/server/PlayerChunkMap.java:[51] Type mismatch: cannot convert from List<Object> to List<PlayerChunk>
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by ThijnBeers** [comment]
Have the same problem

**Comment by mics8128** [comment]
我也有同樣問題
java 1.8.0_77
spigot 1.9.2最新編譯版本 (4/18)

然後我降版HOSE到4/5的版本可以正常編譯
但是玩家一進去伺服器就出現以下錯誤
```
Encountered an unexpected exception
java.lang.VerifyError: Inconsistent stackmap frames at branch target 52
Exception Details:
  Location:
    net/minecraft/server/v1_9_R1/DataWatcher.b(Lnet/minecraft/server/v1_9_R1/PacketDataSerializer;)Ljava/util/List; @52: aload_1
  Reason:
    Type top (current frame, locals[4]) is not assignable to integer (stack map, locals[4])
  Current Frame:
    bci: @24
    flags: { }
    locals: { 'net/minecraft/server/v1_9_R1/PacketDataSerializer', 'java/util/ArrayList', integer, 'net/minecraft/server/v1_9_R1/DataWatcherSerializer' }
    stack: { 'net/minecraft/server/v1_9_R1/DataWatcherSerializer' }
  Stackmap Frame:
    bci: @52
    flags: { }
    locals: { 'net/minecraft/server/v1_9_R1/PacketDataSerializer', 'java/util/ArrayList', integer, 'net/minecraft/server/v1_9_R1/DataWatcherSerializer', integer }
    stack: { }
  Bytecode:
    0x0000000: 014c a700 4d2b c700 07b8 0122 4c2a b601
    0x0000010: 3f3d 1cb8 0142 4e2d c700 1cbb 0144 59bb
    0x0000020: 004f 5913 0133 b700 541c b600 58b6 0063
    0x0000030: b701 45bf 2bbb 0007 592d 1504 b900 6f02
    0x0000040: 002d 2ab9 0148 0200 b700 9cb6 0125 572a
    0x0000050: b601 4c59 3604 1100 ffa0 ffac 2bb0     
  Stackmap Table:
    append_frame(@5,Object[#277],Integer)
    same_frame(@13)
    append_frame(@52,Object[#75],Integer)
    chop_frame(@79,3)

	at net.minecraft.server.v1_9_R1.Entity.<clinit>(Entity.java:115) ~[hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at net.minecraft.server.v1_9_R1.PlayerList.attemptLogin(PlayerList.java:444) ~[hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:118) ~[hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) ~[hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) ~[hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) ~[hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:827) ~[hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) ~[hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:667) ~[hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:566) [hose-1.9.2.jar:git-Spigot-5a40365-b70058a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]

```

**Comment by ausir0726** [comment]
@mics8128  
你執行的時候有加上 -noverify 嗎？
請參閱 
https://github.com/softpak/HOSE/issues/9

**Comment by mics8128** [comment]
哦哦 運作正常 感謝 :+1:
