### ISSUE TITLE
concurrent Modification

### ISSUE THREAD

**Issue by loveyanbei** [softpak/HOSE#24]
Crash report:

[14:27:41] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_91]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.EntityTracker.updatePlayers(EntityTracker.java:180) ~[hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825) ~[hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) ~[hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:676) ~[hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:575) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[14:27:41] [Server thread/ERROR]: This crash report has been saved to: /home/autossh/mc-spigot/./crash-reports/crash-2016-06-24_14.27.41-server.txt
[14:27:41] [Server thread/INFO]: Stopping server
[14:27:41] [Server thread/INFO]: [MapCircuitBoard] Disabling MapCircuitBoard v1.6
[14:27:41] [Server thread/INFO]: [MapPainting] Disabling MapPainting v1.5.9-beta
[14:27:41] [Server thread/INFO]: Finished clean up! You have succesfully purged 0 files.
[14:27:41] [Server thread/INFO]: [scriptcraft] Disabling scriptcraft v3.2.0-2016-03-19
[14:27:41] [Server thread/INFO]: Saving players
[14:27:41] [Server thread/INFO]: 久美稥月 lost connection: Server closed
[14:27:41] [Server thread/INFO]: 久美稥月 left the game.
[14:27:42] [Server thread/INFO]: Saving worlds
[14:27:42] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[14:27:42] [Server thread/INFO]: Saving chunks for level 'world_nether'/Nether
[14:27:42] [Server thread/INFO]: Saving chunks for level 'world_the_end'/The End

**Comment by loveyanbei** [comment]
net.minecraft.server.v1_9_R2.ReportedException: Adding entity to track
        at net.minecraft.server.v1_9_R2.EntityTracker.addEntity(EntityTracker.java:145) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.EntityTracker.track(EntityTracker.java:64) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.WorldManager.a(WorldManager.java:19) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.World.b(World.java:1040) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.WorldServer.b(WorldServer.java:1131) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.World.addEntity(World.java:1033) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.World.addEntity(World.java:957) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.WorldServer.addEntity(WorldServer.java:1084) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.dropItem(CraftWorld.java:337) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at org.bukkit.craftbukkit.v1_9_R2.CraftWorld.dropItemNaturally(CraftWorld.java:376) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:398) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.EntityLiving.die(EntityLiving.java:992) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.EntityZombie.die(EntityZombie.java:556) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity(EntityLiving.java:909) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.EntityMonster.damageEntity(EntityMonster.java:44) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.EntityZombie.damageEntity(EntityZombie.java:182) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.Entity.U_hose(Entity.java:373) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.Entity$U.compute(Entity.java:2738) [hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189) [?:1.8.0_91]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_91]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_91]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_91]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Asynchronous player tracker update!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:327) ~[hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:441) ~[hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        at net.minecraft.server.v1_9_R2.EntityTracker.addEntity(EntityTracker.java:119) ~[hose-1.9.4.jar:git-Spigot-8a048fe-3c19fef]
        ... 22 more

**Comment by loveyanbei** [comment]
记得看一下啊，这个bug是你的release里面的，会直接崩服

**Comment by softpak** [comment]
恩，
這個我知道，
patch也還沒放上去，
現在學期末，
給點時間喘息吧。  囧

**Comment by loveyanbei** [comment]
啊是吗，我今天才考完去，祝考好，等崩服bug消了我再来试试
