### ISSUE TITLE
几个插件和HOSE不能兼容

### ISSUE THREAD

**Issue by loveyanbei** [softpak/HOSE#37]
Multiworld 和 Holographic Display

[11:29:28] [Server thread/ERROR]: Error occurred while enabling MultiWorld v5.2.8 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.World.getPopulators()Ljava/util/List;
        at com.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:245) ~[?:?]
        at net.minecraft.server.v1_11_R1.WorldServer.b(WorldServer.java:121) ~[hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.createWorld(CraftServer.java:901) ~[hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:471) ~[hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at multiworld.data.WorldManager.loadWorld(WorldManager.java:347) ~[?:?]
        at multiworld.data.WorldManager.loadWorlds(WorldManager.java:658) ~[?:?]
        at multiworld.data.DataHandler.load(DataHandler.java:242) ~[?:?]
        at multiworld.data.DataHandler.<init>(DataHandler.java:61) ~[?:?]
        at multiworld.MultiWorldPlugin.onEnable(MultiWorldPlugin.java:256) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:377) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:327) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

[11:29:33] [Server thread/WARN]: [HolographicDisplays] Task #61 for HolographicDisplays v2.2.3 generated an exception
java.lang.NoSuchFieldError: entityList
        at com.gmail.filoghost.holographicdisplays.nms.v1_11_R1.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:113) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_11_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:94) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:75) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:300) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:247) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.task.StartupLoadHologramsTask.run(StartupLoadHologramsTask.java:11) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [hose-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by softpak** [comment]
I`ve already fix this. Please wait for the new release.
