### ISSUE TITLE
1.11.2 crash problem

### ISSUE THREAD

**Issue by xerathyang** [softpak/HOSE#49]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2017/5/24 下午 11:09
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.minecraft.server.v1_11_R1.PersistentVillage.e(SourceFile:195)
	at net.minecraft.server.v1_11_R1.PersistentVillage.a(SourceFile:54)
	at net.minecraft.server.v1_11_R1.EntityVillager.M(EntityVillager.java:103)
	at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:664)
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2041)
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501)
	at net.minecraft.server.v1_11_R1.EntityAgeable.n(EntityAgeable.java:158)
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1894)
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244)
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1690)
	at net.minecraft.server.v1_11_R1.World.h(World.java:1665)
	at net.minecraft.server.v1_11_R1.World.lambda$0(World.java:1440)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.minecraft.server.v1_11_R1.PersistentVillage.e(SourceFile:195)
	at net.minecraft.server.v1_11_R1.PersistentVillage.a(SourceFile:54)
	at net.minecraft.server.v1_11_R1.EntityVillager.M(EntityVillager.java:103)
	at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:664)
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2041)
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501)
	at net.minecraft.server.v1_11_R1.EntityAgeable.n(EntityAgeable.java:158)
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1894)
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244)
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1690)
	at net.minecraft.server.v1_11_R1.World.h(World.java:1665)

-- Entity being ticked --
Details:
	Entity Type: minecraft:villager (net.minecraft.server.v1_11_R1.EntityVillager)
	Entity ID: 179
	Entity Name: Villager
	Entity's Exact location: -38137.37, 76.00, -65523.50
	Entity's Block location: World: (-38138,76,-65524), Chunk: (at 6,4,12 in -2384,-4096; contains blocks -38144,0,-65536 to -38129,255,-65521), Region: (-75,-128; contains chunks -2400,-4096 to -2369,-4065, blocks -38400,0,-65536 to -37889,255,-65025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_11_R1.World.lambda$0(World.java:1440)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayer['XerathYang'/186, l='world', x=-38139.28, y=75.88, z=-65520.88](XerathYang at -38139.28291117576,75.8830426111804,-65520.87656942362)]
	Chunk stats: ServerChunkCache: 697 Drop: 0
	Level seed: 4921539020605143828
	Level generator: ID 04 - customized, ver 0. Features enabled: true
	Level generator options: {"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":0.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":8,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useMansions":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":10,"useLavaLakes":false,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":4,"riverSize":2,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":9,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":9,"goldCount":8,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":8,"diamondCount":3,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":7,"lapisCount":3,"lapisCenterHeight":16,"lapisSpread":21}
	Level spawn location: World: (212,64,256), Chunk: (at 4,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2114170 game time, 143853 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:824)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 159132840 bytes (151 MB) / 512241664 bytes (488 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 5 total; -Xverify:none -Xms512M -Xmx1G -XX:MaxPermSize=128M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 91
	CraftBukkit Information: 
   Running: CraftBukkit version git-Spigot-54ec0b8-7b044de (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) true
   Plugins: { AsyncWorldEditInjector v2.3.0 org.primesoft.asyncworldedit.injector.InjectorBukkit [SBPrime], WorldEdit v6.1.5;4651611 com.sk89q.worldedit.bukkit.WorldEditPlugin [], AsyncWorldEdit v2.3.2 org.primesoft.asyncworldedit.AsyncWorldEditBukkit [SBPrime],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Server console handler: [org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method), org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:761), org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794), org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97), org.bukkit.craftbukkit.libs.jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:215), org.bukkit.craftbukkit.libs.jline.WindowsTerminal.access$000(WindowsTerminal.java:55), org.bukkit.craftbukkit.libs.jline.WindowsTerminal$1.read(WindowsTerminal.java:157), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2349), net.minecraft.server.v1_11_R1.DedicatedServer$2.run(DedicatedServer.java:84)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_11_R1.DedicatedServer$1.run(DedicatedServer.java:59)], RUNNABLE ForkJoinPool.commonPool-worker-1: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_11_R1.CraftCrashReport.call(CraftCrashReport.java:30), net.minecraft.server.v1_11_R1.CrashReportSystemDetails.a(SourceFile:78), net.minecraft.server.v1_11_R1.CrashReport.h(CrashReport.java:126), net.minecraft.server.v1_11_R1.CrashReport.<init>(CrashReport.java:33), net.minecraft.server.v1_11_R1.CrashReport.a(CrashReport.java:320), net.minecraft.server.v1_11_R1.World.lambda$0(World.java:1443), net.minecraft.server.v1_11_R1.World$$Lambda$19/914345865.accept(Unknown Source), java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source), java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source), java.util.stream.AbstractPipeline.copyInto(Unknown Source), java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source), java.util.concurrent.CountedCompleter.exec(Unknown Source), java.util.concurrent.ForkJoinTask.doExec(Unknown Source), java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING ForkJoinPool.commonPool-worker-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], RUNNABLE Netty Server IO #0: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Unknown Source)], WAITING Server thread: [java.lang.Object.wait(Native Method), java.util.concurrent.ForkJoinTask.externalAwaitDone(Unknown Source), java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source), java.util.concurrent.ForkJoinTask.invoke(Unknown Source), java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source), java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source), java.util.stream.AbstractPipeline.evaluate(Unknown Source), java.util.stream.ReferencePipeline.forEach(Unknown Source), java.util.stream.ReferencePipeline$Head.forEach(Unknown Source), net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1421), net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:620), net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814), net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399), net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678), net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576), java.lang.Thread.run(Unknown Source)], WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:278), java.lang.Thread.run(Unknown Source)], WAITING ForkJoinPool.commonPool-worker-4: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:92)], RUNNABLE Signal Dispatcher: [], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77), org.bukkit.craftbukkit.v1_11_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:27), java.lang.Thread.run(Unknown Source)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_11_R1.FileIOThread.c(SourceFile:51), net.minecraft.server.v1_11_R1.FileIOThread.run(SourceFile:30), java.lang.Thread.run(Unknown Source)], WAITING ForkJoinPool.commonPool-worker-3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.lang.ref.Reference.tryHandlePending(Unknown Source), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], WAITING ForkJoinPool.commonPool-worker-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], RUNNABLE Attach Listener: [], RUNNABLE Netty Server IO #1: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Unknown Source)], WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), sun.java2d.Disposer.run(Unknown Source), java.lang.Thread.run(Unknown Source)],}
   Recent tasks from 1948-1978{AsyncWorldEdit:org.primesoft.asyncworldedit.mcstats.MetricsLite$1@31,}
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayer['XerathYang'/186, l='world', x=-38139.28, y=75.88, z=-65520.88](XerathYang at -38139.28291117576,75.8830426111804,-65520.87656942362)]
	Is Modded: Definitely; Server brand changed to 'Hose'
	Type: Dedicated Server (map_server.txt)
經常會發生這樣的情形，大概是5次會有2到3次
還有使用traincarts的時候會無法登入，一直跳出Internal Exception: java.lang.NoSuchFieldError: removeQueue

**Comment by softpak** [comment]
I`ve already fix it. Please build again.
